apiVersion: v1
kind: Service
metadata:
  labels:
    name: ray-blog-svc
  name: ray-blog-svc
  namespace: ray-blog-ns
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: ray-blog
  type: LoadBalancer
