# Generated by Django 2.1.2 on 2018-10-31 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_auto_20181031_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 18, 44, 14, 139948, tzinfo=utc)),
        ),
    ]
