# Generated by Django 2.1.2 on 2018-10-31 22:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0029_auto_20181031_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 22, 47, 41, 577512, tzinfo=utc)),
        ),
    ]
