# Generated by Django 2.1.2 on 2018-11-01 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0032_auto_20181031_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 19, 32, 32, 248941, tzinfo=utc)),
        ),
    ]
