# Generated by Django 2.1.2 on 2018-11-01 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0035_auto_20181101_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 21, 36, 41, 598173, tzinfo=utc)),
        ),
    ]
