# Generated by Django 2.1.2 on 2018-11-01 23:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0036_auto_20181101_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 23, 37, 37, 587914, tzinfo=utc)),
        ),
    ]
