# Generated by Django 2.1.2 on 2018-11-01 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0037_auto_20181101_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='read_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 23, 50, 47, 71520, tzinfo=utc)),
        ),
    ]
